name: Build project
on: [push, pull_request]

jobs:
  sendStartNotification:
    name: Send Start Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
          "username": "GitHub",
          "content": "Am pula mare",
          "embeds": [
            {
              "type": "rich",
              "title": "Build Start",
              "description": "New changes on ${{ github.event.repository.name }} by ${{ github.actor }}",
              "color": 2123412,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}",
                "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
              },
              "url": "https://github.com/***"
            }
          ]
          }' ${{ secrets.DISCORD_WEBHOOK }})
          echo "Webhook server response: $RESPONSE"
 
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build with Unity
        id: build-step
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Create Date Directory
        run: mkdir -p ${{ steps.get_start_date.outputs.start_date }}
        
      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: "archive.zip"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "${{ matrix.targetPlatform }}.zip" # optional string
          overwrite: "true" # optional boolean
          
      - name: Send Discord Notification
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
          "username": "GitHub",
          "content": "Build Results",
          "embeds": [
            {
              "type": "rich",
              "title": "Build Finished ${{ matrix.targetPlatform }} ",
              "description": "Build for ${{ matrix.targetPlatform }} on ${{ github.event.repository.name }} by${{ github.actor }} has ${{ job.status }}",
              "color": 2123412,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}",
                "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
              },
              "url": "https://github.com/***"
            }
          ]
          }' ${{ secrets.DISCORD_WEBHOOK }})
          echo "Webhook server response: $RESPONSE"
